import type { TrackerState } from "../../lib/training";
import type { UserFieldDefinition } from "./user-data-types";

type UserFieldKey = keyof TrackerState["goals"] | keyof TrackerState["profile"];

export const USER_FIELD_REGISTRY: Record<UserFieldKey, UserFieldDefinition> = {
  currentGrade: { key: "currentGrade", category: "climbing", unit: null, destination: "goals" },
  targetGrade: { key: "targetGrade", category: "goal", unit: null, destination: "goals" },
  project: { key: "project", category: "goal", unit: null, destination: "goals" },
  focus: { key: "focus", category: "goal", unit: null, destination: "goals" },
  name: { key: "name", category: "identity", unit: null, destination: "profile" },
  location: { key: "location", category: "identity", unit: null, destination: "profile" },
  age: { key: "age", category: "identity", unit: "years", destination: "profile" },
  sex: { key: "sex", category: "identity", unit: null, destination: "profile" },
  height: { key: "height", category: "identity", unit: "cm", destination: "profile" },
  weight: { key: "weight", category: "identity", unit: "kg", destination: "profile" },
  wingspan: { key: "wingspan", category: "identity", unit: "cm", destination: "profile" },
  apeIndex: { key: "apeIndex", category: "identity", unit: "cm", destination: "profile" },
  dominantHand: { key: "dominantHand", category: "identity", unit: null, destination: "profile" },
  handSize: { key: "handSize", category: "identity", unit: null, destination: "profile" },
  climbingExperience: { key: "climbingExperience", category: "climbing", unit: "years", destination: "profile" },
  maxBoulder: { key: "maxBoulder", category: "climbing", unit: null, destination: "profile" },
  maxSport: { key: "maxSport", category: "climbing", unit: null, destination: "profile" },
  styleStrengths: { key: "styleStrengths", category: "climbing", unit: null, destination: "profile" },
  styleWeaknesses: { key: "styleWeaknesses", category: "climbing", unit: null, destination: "profile" },
  fingerStrength: { key: "fingerStrength", category: "capacity", unit: null, destination: "profile" },
  fingerEndurance: { key: "fingerEndurance", category: "capacity", unit: null, destination: "profile" },
  pullStrength: { key: "pullStrength", category: "capacity", unit: "reps", destination: "profile" },
  shoulderCapacity: { key: "shoulderCapacity", category: "capacity", unit: null, destination: "profile" },
  coreTension: { key: "coreTension", category: "capacity", unit: null, destination: "profile" },
  hipAnkleMobility: { key: "hipAnkleMobility", category: "capacity", unit: null, destination: "profile" },
  weeklyAvailability: { key: "weeklyAvailability", category: "availability", unit: "days", destination: "profile" },
  trainingLoad: { key: "trainingLoad", category: "availability", unit: null, destination: "profile" },
  sleepBaseline: { key: "sleepBaseline", category: "recovery", unit: "hours", destination: "profile" },
  stressBaseline: { key: "stressBaseline", category: "recovery", unit: "0-10", destination: "profile" },
  boardSetup: { key: "boardSetup", category: "equipment", unit: null, destination: "profile" },
  equipment: { key: "equipment", category: "equipment", unit: null, destination: "profile" },
  strengths: { key: "strengths", category: "coaching", unit: null, destination: "profile" },
  limiters: { key: "limiters", category: "coaching", unit: null, destination: "profile" },
  injuryHistory: { key: "injuryHistory", category: "health", unit: null, destination: "profile" },
  currentPain: { key: "currentPain", category: "health", unit: "0-10", destination: "profile" },
  skinTolerance: { key: "skinTolerance", category: "health", unit: null, destination: "profile" },
  nutritionRisk: { key: "nutritionRisk", category: "health", unit: null, destination: "profile" },
  recoveryNotes: { key: "recoveryNotes", category: "recovery", unit: null, destination: "profile" },
  coachNotes: { key: "coachNotes", category: "coaching", unit: null, destination: "profile" },
  questionnaireCompleted: { key: "questionnaireCompleted", category: "preference", unit: "boolean", destination: "profile" },
  questionnaireCompletedAt: { key: "questionnaireCompletedAt", category: "preference", unit: null, destination: "profile" },
  questionnaireVersion: { key: "questionnaireVersion", category: "preference", unit: null, destination: "profile" }
};
