import { useState } from "react";
import { Activity, ArrowRight, Camera, CheckCircle2, ClipboardList, Film, LayoutDashboard, LogIn, Mountain, Play, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { ChoiceCard } from "@/components/climb/ChoiceCard";
import { GradeBadge } from "@/components/climb/GradeBadge";
import { HoldMark, RopeKnotMark, RouteTraceMark } from "@/components/climb/ClimbMarks";
import { LoadScale } from "@/components/climb/LoadScale";
import { RecoverySignal } from "@/components/climb/RecoverySignal";
import { SessionCard } from "@/components/climb/SessionCard";

type Flow = "access" | "dashboard" | "plan" | "log" | "video" | "profile";
const flows: { id: Flow; label: string; icon: typeof LogIn }[] = [{ id: "access", label: "Acceso", icon: LogIn }, { id: "dashboard", label: "Dashboard", icon: LayoutDashboard }, { id: "plan", label: "Plan", icon: Mountain }, { id: "log", label: "Log", icon: ClipboardList }, { id: "video", label: "Video", icon: Film }, { id: "profile", label: "Perfil", icon: UserRound }];

export function ProductFlowMockup() {
  const [flow, setFlow] = useState<Flow>("access");
  return <main className="min-h-svh bg-paper text-foreground"><header className="border-b border-border bg-card/85 px-4 py-4 backdrop-blur sm:px-8"><div className="mx-auto flex max-w-7xl items-center justify-between"><div><p className="text-xs font-semibold tracking-[.16em] text-river uppercase">Climb 4W</p><p className="font-semibold">Mockups de producto</p></div><a className="text-sm font-semibold text-river hover:underline" href="?mockup=design-system">Sistema de diseño →</a></div></header><div className="mx-auto flex max-w-7xl flex-col gap-6 p-4 sm:p-6 lg:flex-row lg:p-8"><nav className="flex gap-1 overflow-x-auto rounded-2xl border bg-card p-2 lg:w-52 lg:flex-col lg:self-start" aria-label="Flujos del producto">{flows.map(({ id, label, icon: Icon }) => <button key={id} type="button" onClick={() => setFlow(id)} className={`flex min-h-11 shrink-0 items-center gap-2 rounded-xl px-3 text-left text-sm font-semibold ${flow === id ? "bg-sandstone text-river" : "hover:bg-muted"}`}><Icon className="size-4" />{label}</button>)}</nav><section className="min-w-0 flex-1">{flow === "access" ? <AccessMockup /> : null}{flow === "dashboard" ? <DashboardMockup /> : null}{flow === "plan" ? <PlanMockup /> : null}{flow === "log" ? <LogMockup /> : null}{flow === "video" ? <VideoMockup /> : null}{flow === "profile" ? <ProfileMockup /> : null}</section></div></main>;
}

function PageTitle({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <div className="mb-6"><p className="text-xs font-semibold tracking-[.16em] text-river uppercase">{eyebrow}</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">{title}</h1><p className="mt-2 text-muted-foreground">{description}</p></div>; }

function AccessMockup() { return <div className="mx-auto max-w-md"><PageTitle eyebrow="01 · Registro y acceso" title="Volvé a la pared" description="El acceso mantiene el foco en tu práctica, no en el formulario." /><Card><CardHeader className="text-center"><div className="mx-auto flex size-12 items-center justify-center rounded-full bg-sandstone text-river"><RopeKnotMark className="size-7" /></div><CardTitle className="mt-3">Iniciá sesión</CardTitle><CardDescription>Tu plan y tus registros te esperan.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="space-y-2"><Label htmlFor="email">Correo electrónico</Label><Input id="email" placeholder="nombre@correo.com" /></div><div className="space-y-2"><Label htmlFor="password">Contraseña</Label><Input id="password" type="password" value="password" readOnly /></div><Button className="w-full"><RopeKnotMark className="size-5" />Continuar</Button><div className="flex justify-between text-sm"><button className="text-river hover:underline">Crear cuenta</button><button className="text-river hover:underline">Olvidé mi contraseña</button></div></CardContent></Card></div>; }

function DashboardMockup() { return <><PageTitle eyebrow="02 · Dashboard" title="Tu semana, de un vistazo" description="La próxima acción y la recuperación toman el centro." /><div className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><Card><CardHeader><CardTitle>Próxima sesión</CardTitle><CardDescription>Martes · Semana 1</CardDescription></CardHeader><CardContent><SessionCard /><Button className="mt-4 w-full"><Play className="size-4" />Iniciar sesión</Button></CardContent></Card><div className="space-y-5"><RecoverySignal /><Card><CardHeader><CardTitle>Progresión</CardTitle><CardDescription>Tu grado actual y objetivo.</CardDescription></CardHeader><CardContent className="flex flex-wrap gap-3"><GradeBadge grade="blue" /><ArrowRight className="mt-1 size-4 text-muted-foreground" /><GradeBadge grade="yellow" /></CardContent></Card></div></div></> }

function PlanMockup() { return <><PageTitle eyebrow="03 · Plan" title="Una ruta a la vez" description="El plan usa una tarjeta clara para decidir qué hacer hoy." /><div className="grid gap-5 lg:grid-cols-[.85fr_1.15fr]"><Card><CardHeader><CardTitle>Semana 1</CardTitle><CardDescription>Seleccioná una sesión.</CardDescription></CardHeader><CardContent className="space-y-2"><ChoiceCard label="W1D1 · Limit + fuerza" description="75 min · Intensa" selected mark={<HoldMark className="size-7" />} /><ChoiceCard label="W1D2 · Técnica" description="60 min · Moderada" mark={<RouteTraceMark className="size-7" />} /></CardContent></Card><div className="space-y-5"><SessionCard /><Card><CardHeader><CardTitle>Objetivo del día</CardTitle><CardDescription>Resolver movimientos potentes con tensión y descanso.</CardDescription></CardHeader><CardContent><div className="flex flex-wrap gap-2"><GradeBadge grade="green" /><GradeBadge grade="blue" /><GradeBadge grade="yellow" /></div><Button className="mt-5 w-full">Ver sesión guiada <ArrowRight className="size-4" /></Button></CardContent></Card></div></div></> }

function LogMockup() { const [load, setLoad] = useState(7); return <><PageTitle eyebrow="04 · Log" title="Registrá lo que pasó" description="Datos simples que vuelven útiles tus decisiones de entrenamiento." /><div className="grid gap-5 lg:grid-cols-2"><Card><CardHeader><CardTitle>Carga de sesión</CardTitle><CardDescription>¿Cómo se sintió el esfuerzo total?</CardDescription></CardHeader><CardContent className="space-y-5"><LoadScale value={load} onChange={setLoad} /><div className="grid grid-cols-2 gap-3"><div><Label>Dolor</Label><p className="mt-1 text-3xl font-semibold text-clay">3/10</p></div><div><Label>Mejor link</Label><p className="mt-1 text-3xl font-semibold text-river">32</p></div></div><Button className="w-full"><CheckCircle2 />Guardar sesión</Button></CardContent></Card><RecoverySignal /></div></> }

function VideoMockup() { return <><PageTitle eyebrow="05 · Video" title="Mirá el movimiento" description="Una revisión concreta, con observaciones que sirven para la próxima sesión." /><div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><Card><CardContent className="p-4"><div className="grid aspect-video place-items-center rounded-xl bg-ink text-paper"><div className="text-center"><Camera className="mx-auto size-9" /><p className="mt-3 font-semibold">Subí un video para analizar</p><p className="mt-1 text-sm text-paper/70">MP4, MOV o WebM</p></div></div><Button variant="outline" className="mt-4 w-full">Seleccionar video</Button></CardContent></Card><Card><CardHeader><CardTitle>Checklist técnico</CardTitle><CardDescription>Guardá una señal clara por sesión.</CardDescription></CardHeader><CardContent className="space-y-3"><ChoiceCard label="Cortes de pie" description="Nivel medio" selected mark={<RouteTraceMark className="size-6" />} /><ChoiceCard label="Tensión corporal" description="Para revisar" mark={<HoldMark className="size-6" />} /><Button className="w-full">Guardar análisis</Button></CardContent></Card></div></> }

function ProfileMockup() { return <><PageTitle eyebrow="06 · Perfil" title="Tu perfil de escalador" description="Lo esencial arriba; el detalle siempre editable." /><div className="grid gap-5 xl:grid-cols-[.8fr_1.2fr]"><Card><CardContent className="flex flex-col items-center p-6 text-center"><div className="grid size-20 place-items-center rounded-full bg-sandstone text-river"><UserRound className="size-9" /></div><h2 className="mt-4 text-xl font-semibold">Mateo Sautón</h2><p className="text-muted-foreground">Salta · 28 años</p><div className="mt-5 flex gap-2"><GradeBadge grade="blue" /><GradeBadge grade="yellow" /></div></CardContent></Card><Card><CardHeader><CardTitle>Cómo escalás</CardTitle><CardDescription>Actualizá estos datos cuando cambie tu entrenamiento.</CardDescription></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2"><ChoiceCard label="Boulder" description="Disciplina principal" selected mark={<HoldMark className="size-6" />} /><ChoiceCard label="3 sesiones" description="Disponibilidad semanal" mark={<RouteTraceMark className="size-6" />} /><Button className="sm:col-span-2">Editar perfil</Button></CardContent></Card></div></> }
